openapi: 3.1.0
info:
  title: Clipboard History MCP
  version: '1.0'
paths: 
  /clipboard:
    get:
      summary: 'Get recent clipboard history'
      parameters:
        - name: n
          in: query
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: 'clipboard history'
          content:
            application/json:
              schema:
                type: object
                properties:
                  clips:
                    type: array
                    items:
                      $ref: '#/components/schemas/Clip'
  /clipboard_summary:
    get:
      summary: 'Get summary of recent clipboard history'
      parameters:
        - name: n
          in: query
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: 'clipboard summary'
          parameters:
            name: n
            in: query
            schema:
              type: integer
              default: 10
          responses:
            '200':
              description: 'clipboard summary'
              content: 
                application/json:
                  schema:
                    type: object
                    properties:
                      summary:
                        type: string
                      
components:
  schemas:
    clips:
      type: object
      properties:
        text:
          type: string
        ts:
          type: string
          format: date-time